### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by maboroshin** [maboroshin/qBittorrentDarktheme#3]
Unknown issue with dark theme. Probably need to improve the program, not only the theme.

Let me know if you find a solution.

**Unsolved color**
* [Checkbox on the transfer list's context menu](https://github.com/maboroshin/qBittorrentDarktheme/issues/3#issuecomment-591917158)

**Corrected on ver 4.5.0**
* [Icons: Error, Warning](https://github.com/maboroshin/qBittorrentDarktheme/issues/3#issuecomment-753669084)

**Corrected on ver 4.3.0**
* [x]  [Link text color](https://github.com/maboroshin/qBittorrentDarktheme/issues/3#issuecomment-591906717) (Blue problem)
* [x] [Availability color](https://github.com/maboroshin/qBittorrentDarktheme/issues/3#issuecomment-591908434) (Changed)
* [x]  [Log text color](https://github.com/maboroshin/qBittorrentDarktheme/issues/3#issuecomment-591907835) (Include same blue problem)

**Corrected on ver 4.2.2**
* [x]  [Menu's margin](https://github.com/maboroshin/qBittorrentDarktheme/issues/3#issuecomment-591921160)

----

Sample references
* [Sample code of qss](https://stackoverflow.com/questions/32008491/style-of-html-integrated-qstring/32020068#32020068)
* [Sample code of qss2](https://stackoverflow.com/questions/932092/default-html-style-for-controls-in-the-qt-library/932257)
* [setDefaultStyleSheet](https://doc.qt.io/qt-5/qtextdocument.html#defaultStyleSheet-prop)
* [Qt Style Sheets Examples](https://doc.qt.io/qt-5/stylesheet-examples.html)

**Comment by maboroshin** [comment]
* [x]  **Link text color** (blue) is not visible** in Option and About. Also RSS reader, Update dialog.

If it is changed to Upload text color, it will visible in both dark and white. Visible in many situations without writing a new QSS (similer CSS). 

Its value is : `#3299ff` (`50, 153, 255`) from [src/gui/properties/speedplotview.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/properties/speedplotview.cpp#L173)
![link7](https://user-images.githubusercontent.com/41102508/75437886-4c68e580-599a-11ea-8977-8f7e5bdd9b4a.png)

HTML RGB (setText, setHtml)
[src/gui/aboutdialog.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/aboutdialog.cpp#L51)
![link1](https://user-images.githubusercontent.com/41102508/75437718-057af000-599a-11ea-8b06-20b95a395937.png)

[aboutdialog.ui](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/aboutdialog.ui#L100) ?  (QLabel a href)
![link2](https://user-images.githubusercontent.com/41102508/75437719-057af000-599a-11ea-98a1-2ecef767c8dd.png)

[src/gui/thanks.html](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/thanks.html) / 
[src/gui/gpl.html](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/gpl.html#L26) (HTML via aboutdialog.cpp)
![link3](https://user-images.githubusercontent.com/41102508/75437722-06138680-599a-11ea-9a37-26856bf2b46f.png)


[src/gui/optionsdialog.ui](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/optionsdialog.ui#L2299) ? (QLabel a href)
![link4](https://user-images.githubusercontent.com/41102508/75437723-06ac1d00-599a-11ea-959b-e5c6c40fe2d0.png)

[same](https://github.com/qbittorrent/qBittorrent/blob/matser/src/gui/optionsdialog.ui#L2957)
![link5](https://user-images.githubusercontent.com/41102508/75437725-06ac1d00-599a-11ea-9fbc-fc300ed0ea88.png)

[src/gui/advancedsettings.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/advancedsettings.cpp#L332) used  [makeLink](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/advancedsettings.cpp#L48) (Qlabel a href)
![link6](https://user-images.githubusercontent.com/41102508/75437781-217e9180-599a-11ea-8011-6e18175541c1.png)

[src/gui/mainwindow.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/mainwindow.cpp#L1821) (QString a href)
![qbqa](https://user-images.githubusercontent.com/41102508/77610351-ca9eb480-6f65-11ea-8f23-f7fd8a939c1c.jpg)


[src/gui/rss/rsswidget.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/rss/rsswidget.cpp#L481) (QString)
RSS reader. (No image)

**Comment by maboroshin** [comment]
* [x]  **Log text color** seems to have the same problem as Transfer list.

But easy to do. It should change blue to `#3299ff`. On many darks, this initial value `#3299ff` will remain visible.

`Convert the Log widget to use custom View/Model #12144` of Pull requests in official qBittorrent, in progress.

HTML RGB (QString font color=)
[src/gui/executionlogwidget.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/executionlogwidget.cpp#L91)
![log](https://user-images.githubusercontent.com/41102508/75438059-a79ad800-599a-11ea-9192-d339f8f9940c.png)

**Comment by maboroshin** [comment]
* [x] **Progress/Availability color** is not dark. (White and blue)

This code is: https://github.com/maboroshin/qBittorrentDarktheme/issues/5#issuecomment-922402612

~~But easy to do. It should change white to gray, e.g. `#c0c0c0` (Qt::lightGray). The contrast is reduced.~~

~~Internal RGB: [Qt::white](https://doc.qt.io/qt-5/qt.html#GlobalColor-enum), QT::blue~~

[src/gui/properties/piecesbar.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/properties/piecesbar.cpp#L114)<br>
[src/gui/properties/downloadedpiecesbar.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/properties/downloadedpiecesbar.cpp#L139) / [pieceavailabilitybar.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/properties/pieceavailabilitybar.cpp#L140)
![Availability](https://user-images.githubusercontent.com/41102508/75438144-cf8a3b80-599a-11ea-82f5-13a8e57993ab.png)

**Comment by maboroshin** [comment]
**Margin and text color** with right-click on the transfer list.

**Green**: [transferlistwidget.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/transferlistwidget.cpp#L1089) - [tristateaction.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/tristateaction.cpp#L38) - [tristatewidget.cpp](https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/private/tristatewidget.cpp#L39)
I don't know the element name. Changes are possible but partial. The background color is changed, but text color and the margin remains.
![qbContext2](https://user-images.githubusercontent.com/41102508/75440266-cef3a400-599e-11ea-8cbf-44ef82a99e53.png)

Images by adem4ik.
> ![image](https://user-images.githubusercontent.com/4707112/77821418-92cd7380-7103-11ea-9c5f-dbf98389f6d3.png)
> ![image](https://user-images.githubusercontent.com/4707112/77821392-5d288a80-7103-11ea-95c7-a1f02b01178e.png)

Different font than the default.

**Comment by maboroshin** [comment]
Crrected: ~~Cannot be separated by CSS (QSS). I am trying. When I narrow down here, others narrow down and become invisible.~~

* [x]  **Orage**: (On ver 4.2.2, Orange issue only corrected)
Selector is the same as right-clicking on a column.
* `QTabWidget QStackedWidget QTreeView QMenu::item`

And There are can't used.
* `QTabWidget QStackedWidget QHeaderView QMenu::item`
* `QTabWidget QStackedWidget QHeaderView QTreeView QMenu::item`
* `QTabWidget QStackedWidget QTreeView QHeaderView QMenu::item`

Thus, they cannot be distinguished.

![qtList2](https://user-images.githubusercontent.com/41102508/75617100-cf0dc280-5b9d-11ea-846d-6425574ccae6.png)

Same problem as orange. Tool button context menu. Making this check visible will make other margins wider.

* [x]  **Yellow** : (On ver 4.2.2, Yellow issue corrected)
 Common selector:<br>
* `QMenu::item`

There are can't used.<br>
* `QToolBar QMenu::item`

![qbtool](https://user-images.githubusercontent.com/41102508/75617263-26ad2d80-5ba0-11ea-947a-7874faf9cd6e.png)

**Comment by maboroshin** [comment]
Same problem as orange. Making this check visible will make other margins wider

Yellow: Common selector:<br>
* `QMenu::item`

There are can't used.<br>
* `QToolBar QMenu::item`

![qbtool](https://user-images.githubusercontent.com/41102508/75617263-26ad2d80-5ba0-11ea-947a-7874faf9cd6e.png)

**Comment by maboroshin** [comment]
Orange and yellow fixes for 4.2.2 and above

```
QMenu::item {
  padding-left: 4px; /* Add */
}

QMenuBar QMenu::item QMenu::item { /* sub menu */
  padding-left: 4px; /* Add */
}

QTabWidget QStackedWidget QTreeView QMenu::item { /* transfer list : context menu , column context menu */
  padding-left: 4px;
}
```

**Comment by charmesal** [comment]
I'm also having color issues but nothing like you have described already. Some text is still dark and the background of some fields are still white. This could be an issue with Gnome but I am unable to find anything about this yet. I'm still a beginner when it comes to programming but I might be able to help with testing.
![Screenshot from 2020-04-02 00-27-14](https://user-images.githubusercontent.com/13157582/78192827-3d81c100-7479-11ea-82e2-b3b3ffe3e309.png)

**Comment by maboroshin** [comment]
* [x] Icons: Error, Warning

Can't change.

![image](https://user-images.githubusercontent.com/41102508/103487880-d9e35480-4e4b-11eb-9445-a77266da2a49.png)

**Comment by b-user** [comment]
"fixed" in 4.5.0
